apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 2
  template:
  # this is exactly the same content of ./pod.yaml
    metadata:
      labels:
        app: "server"
    spec:
      containers:
        - name: node-server
          image: "nicolaslopes/hello-node:v9.1"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 1
            successThreshold: 1
          envFrom:
            - configMapRef:
                name: node-server-env
            - secretRef:
                name: node-server-secret