apiVersion: v1
kind: Service
metadata:
  name: node-server-load-balancer-service
spec:
  selector:
    app: node-server
  type: LoadBalancer
  ports:
    - name: node-server-http
      port: 80
      protocol: TCP