apiVersion: v1
kind: Service
metadata:
  name: node-server-service
spec:
  selector:
    app: node-server
  type: ClusterIP
  ports:
    - name: node-server-http
      port: 80
      # we can add a targetPort to refer to the container's port. when no `targetPort` is specified
      # will use the same value of the port.
      protocol: TCP